#!/usr/bin/env python

from beacon.beacon import Beacon
import daemon
import lockfile

context = daemon.DaemonContext(
    pidfile=lockfile.FileLock('/var/run/beacon.pid'),
    )

with context:
    Beacon()
